[package]
name = "advent"
version = "0.1.0"
authors = ["Nikhil Benesch <nikhil.benesch@gmail.com>"]

[dependencies]
chrono = "0.4.6"
itertools = "0.8.0"
regex = "1.1.0"
simple-error = "0.1.13"

[[bin]]
name = "day4"
path = "src/day4.rs"